# Generated by Django 5.0 on 2024-10-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
